# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Caue Queiroz
email: cauenqueiroz@gmail.com
description: Um blog de um desenvolvedor Front End e entusiasta de novas tecnologias.
baseurl: ""
url: "http://cauequeiroz.com.br"

# Build settings
markdown: kramdown
permalink: /:title
